### ISSUE TITLE
Windowsデータ処理でエラー

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#50]
## ライブラリ設定
・文字コードを、S-JIS、CP932 に設定し試行

## フロー
・データ配置し、プレビューでエラー
・文字コード変換コマンドの出力でエラー

## 注意
・データソース指定の無い旧版のフロー
・該当ファイルは、新板での「ライブラリ」が未接続
   → これが原因かもしれない
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/444193bb-3625-4fd8-91ea-16c781da3d0c)

![image](https://github.com/sabanyan/streamcat-web/assets/76473786/00a9fa91-e1cb-4b25-bb80-5a98431615ba)

## エラー
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/fa8ee1df-7ecf-4ad7-a3cf-861e283a4e44)

**Comment by hiroshi80** [comment]
## 原因
- Frameの`path`に設定されているファイルが存在しないため上記エラーが発生していると考えられる
- アーカイブからインポートしたフローを用いてるようなので、フローが参照するFrameがアーカイブに含まれてなかったと思われる
- Frameが含まれていない原因は分からない、古いアーカイブのようなのでアーカイブを手作業で編集したか過去に存在した不具合などによってFrameが脱落した可能性がある

**Comment by hiroshi80** [comment]
## 対応
不正な状態から発生したエラーと思われるので本件を閉じる
