### ISSUE TITLE
旧ライブラリで作成したデータのダウンロードでエラー

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#51]
## ライブラリ
・ファイルを、ダウンロード実施

## 注意
・旧版のフローとデータ → 新版へ移行 したフローのデータで発生
・新版上で、ファイルアップロードしたデータは、ダウンロードに成功した

## エラー発生
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/e76a469d-7872-4ac8-8373-70aeb7eab596)

**Comment by hiroshi80** [comment]
## 原因
[この理由](https://github.com/sabanyan/streamcat-store/issues/50#issuecomment-1825084581)によりFrameのpathに設定されているファイルが存在しないため発生するエラーと思われる

## 対応
不正な状態から発生したエラーと思われるので本件を閉じる
