### ISSUE TITLE
旧ライブラリで作成したデータの削除が失敗する

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#52]
旧版フローを移行した中で、データ削除できないものあり

## エラー
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/2187d8fc-81ad-4ae0-8994-43495567734c)

**Comment by hiroshi80** [comment]
## 原因
[この理由](https://github.com/sabanyan/streamcat-store/issues/50#issuecomment-1825084581)によりFrameのpathに設定されているファイルが存在しないため発生するエラーと思われる

## 対応
不正な状態から発生したエラーと思われるので本件を閉じる
