### ISSUE TITLE
ライブラリ：フォルダの複製時にファイル存在なしとエラーになる

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#53]
## 状況
・ライブラリ上で、フローとデータを格納したフォルダを複製

## 注意
・データソース指定の無い旧版のフロー
・該当ファイルは、新版での「ライブラリ」が未接続
   → これが原因かもしれない
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/444193bb-3625-4fd8-91ea-16c781da3d0c)

![image](https://github.com/sabanyan/streamcat-web/assets/76473786/00a9fa91-e1cb-4b25-bb80-5a98431615ba)

## エラー
・データファイルが存在しないため失敗とのエラーが表示され、複製されず
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/fa19d645-747e-454a-88a6-8f6355eb6822)

**Comment by hiroshi80** [comment]
## 原因
[この理由](https://github.com/sabanyan/streamcat-store/issues/50#issuecomment-1825084581)によりFrameのpathに設定されているファイルが存在しないため発生するエラーと思われる

## 対応
不正な状態から発生したエラーと思われるので本件を閉じる
