### ISSUE TITLE
フローのダウンロード、アップロードでファイルが消える

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#54]
## 状況
・フローとデータのあるフォルダを、「フローのダウンロード」 実行
・ダウンロードしたファイルを、「フローのアップロード」実行

## 結果
・アップロードしたフォルダに、データファイルが含まれていない

## 元ファイル群
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/748e0171-8594-47d5-934c-bdb683df3850)

## 復元ファイル群
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/7944748b-e287-4306-93e3-bd5b6a177f22)

**Comment by hiroshi80** [comment]
## 原因
- フローのダウンロードは、指定したフローとそのフローが参照するサブフローやFrameを纏めてダウンロードする機能である
- そのため、フローが参照しないFrameは含めない仕様である
