### ISSUE TITLE
複製したFrameの文字コードと改行コードの設定が初期値に戻る

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#55]
S-JISなど、文字・改行コードを変更したファイルを
複製した場合、初期状態に戻ってしまう。

**Comment by hiroshi80** [comment]
## 原因
Frameの複製において文字コードと改行コードを複製元から引き継げていなかった

## 修正
複製元Frameから引き継ぐよう修正した(1f76fa0a33da68db3f2414798fba15985ce590b3)
