### ISSUE TITLE
フローのダウンロードで取得したアーカイブにおいてFrameの文字コードと改行コードの設定値が失われる

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#57]
## 懸念
バックアップ用途で活用する場合に、問題になりそう。

## 活用例
フロー、データをフォルダ毎バックアップし、フローのアップロードでリストアする

## 問題点
- フローのアップロード後に、文字・改行コードを編集し直す必要あり
    - 負荷あり
    - どのファイルを編集すべきかが、明示的でない

- 気づかずにフロー実行すると、エラーか、意図と異なる出力になる恐れあり

**Comment by hiroshi80** [comment]
## 修正
- Frameの文字コードと改行コードをJSONファイルに格納し、これをフローのアーカイブに含めるようにした。そのためアーカイブ内においてFrameはCSVファイルとJSONファイルの2つのファイルで保存される (ec5936ae9696a46d72e5c82e9ebbe7273ab9eb13)

  <img width="368" alt="スクリーンショット 2023-11-24 21 40 04" src="https://github.com/sabanyan/streamcat-store/assets/46466792/a467ca0c-abb7-487e-a07e-04b62d987945">
- インポートではJSONファイルから文字コードと改行コードが復元される
