### ISSUE TITLE
移動先に同じラベルのDatumが存在する場合は移動できない

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#59]
## 挙動：拡張子違いのファイル名データの発生
ファイルのアップロードで、ライブラリに格納できる

## 挙動：ライブラリでの移動
拡張子違い（CSV、TXT）のファイルを、移動する場合に、
移動先に拡張子を除く同名ファイルある場合、移動ができない

## 関連
https://github.com/sabanyan/streamcat-web/issues/230

**Comment by hiroshi80** [comment]
### 現状
移動先に同じラベルのDatumが存在する場合、移動したDatumのラベル名の末尾に`_2`を付加して正常に移動できた
