### ISSUE TITLE
一般ユーザのフローのダウンロードとアップロード

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#60]
## 現状
一般ユーザはフローのダウンロードとアップロードができない

## 懸念
- 活用例：バックアップ目的で、フローを保存、復元ができない
- 活用例：リソースとの紐づけを切った、新しい実行環境を作りたい
    - 一般ユーザのプロジェクトで、テストしたいケースを想定
    - フォルダの複製では、データも複製されるが、フローの紐づけ先は元データのまま
        - 作成者は、混乱するのではないか？

## 議論
- 状況の理解：そのユーザがアクセスできないリソースをダウンロードさせない為？
   - そのプロジェクトの管理者は、フローをダウンロード可能にできないか？
       - 例  権限のないリソースが含まれる場合は、ダウンロードが失敗する

**Comment by hiroshi80** [comment]
#40 で既に挙がっているので本件を閉じる
