### ISSUE TITLE
コマンドconvtocp932 が機能していない

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#61]
このコマンドの実行結果は、変換がされてないようで、後続のコマンドが文字化けやエラーになる

## 現象
■ 文字化け例  行数カウント
d43 のプレビュー結果
![image](https://github.com/sabanyan/streamcat-store/assets/76473786/01750826-445c-4ae7-b3db-1d2ba58bc339)

![image](https://github.com/sabanyan/streamcat-store/assets/76473786/c8248992-49d9-402f-ab25-078359788b24)

■ エラー  計算 ・・・  項目名を計算式で参照
d40 のプレビュー結果
![image](https://github.com/sabanyan/streamcat-store/assets/76473786/70b1149f-34fb-46db-b074-59beb36765bf)

![image](https://github.com/sabanyan/streamcat-store/assets/76473786/f4c11fe8-affb-45b7-9836-f14e2eef0d4f)

## データ
[日本語Windowsのデータ.csv](https://github.com/sabanyan/streamcat-store/files/13465705/Windows.csv)

**Comment by hiroshi80** [comment]
## 原因
- [日本語Windowsのデータ.csv](https://github.com/sabanyan/streamcat-store/files/13465705/Windows.csv)は42Byteしかないので、文字コードは’UNKNOWN’と判定される
- `convtocp932`と`convtoutf8`は入力データの文字コードが`UNKNOWN`の場合は、`UTF-8`と見做して変換処理をする
  ```python
  if nysol_module.encoding is None or nysol_module.encoding == 'UNKNOWN':
      # 入力データの文字コードが未判定の場合
      # 判定してもわからなかった場合はUTF-8で試してみる
      source_encoding = 'utf-8'
      source_newline = '\n'
  ```

## 対応
アップロードしたファイルの文字コードをcp932に設定すれば、正しく変換される

1. ライブラリでファイルの文字コードをcp932に設定する
    <img width="640" alt="スクリーンショット 2024-12-04 15 00 25" src="https://github.com/user-attachments/assets/35b1f5d0-550d-43f2-af28-d0c68897e47c">
2. NYSOLコマンドで処理する前に`convtoutf8`コマンドを挟む
    <img width="128" alt="スクリーンショット 2024-12-04 15 02 11" src="https://github.com/user-attachments/assets/58636594-fe23-4fcc-a9cc-ee8f9786d213">
3. `d3`のプレビュー結果
    <img width="256" alt="スクリーンショット 2024-12-04 15 02 58" src="https://github.com/user-attachments/assets/8cbd2a22-c9a2-4172-b974-18293166f26e">
