### ISSUE TITLE
反復波形図のペインの説明文が正しくない

### ISSUE THREAD

**Issue by Kentaro-Yamada** [sabanyan/streamcat-store#62]
説明文にタイピングミス、体言止め・ですます調が混在している。

## 問題箇所１
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/34d05f78-a577-401a-85d6-b0d7c4fe348e)

現状
```
起点列
各反復波形の時間軸の起点を指定n次の横軸列は、この起点からの経過時間を指定
```

修正
```
起点列
各反復波形の時間軸の起点の項目名を指定します＜改行＞
横軸列は、起点からの経過時間の項目名を指定します
```
## 問題箇所２
![image](https://github.com/sabanyan/streamcat-web/assets/76473786/9de3f167-de3b-45ce-bbab-3768abdc9d8e)

現状
```
データ系列
データ系列を表す項目名（復数可、順序は指定不可）を指定します
指定した項目の値（復数項目時はそれぞれの値の組合せ）を系列として設定します


グループ化属性
```

修正
```
データ系列（必須）
1つの波形を1つの系列とし、波形の反復のキー項目を指定します
項目名は復数指定でき、指定した複数の項目の値の組合せを系列とします


グループ化属性（省略可）
複数のデータ系列（波形）を、グループで比較したい場合に指定します
良品、不良品などの波形単位の属性の項目名を指定します
```

**Comment by hiroshi80** [comment]
## 修正
以下の通り文言を修正した (b70f7f4b04e6cc91f1329c09d3f773c61c59b052)

<img width="256" alt="スクリーンショット 2023-11-26 16 15 12" src="https://github.com/sabanyan/streamcat-web/assets/46466792/af98599d-05ec-4dfd-bac5-b930ff1dc6de">
<img width="256" alt="スクリーンショット 2023-11-26 16 16 00" src="https://github.com/sabanyan/streamcat-web/assets/46466792/80feb44b-da1b-47c0-b13f-62465214eca5">
